server:
  port: 80
#

cloud:
  aws:
    credentials:
      access-key: ----
      secret-key: ----
    region:
      static: ----
    stack:
      auto: false

application:
  bucket:
    name: ----

#
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/aws-s3.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

